name = "PzGr33 QOL"
author = "isky"
prefix = "pzgr"
mainprefix = "pzgr33"

[files]
include = ["mod.cpp", "meta.cpp", "CHANGELOG.md", "logo.paa"]
exclude = ["README.md", "*.png", "*.tga"]

[version]
git_hash = 0 # Default: 8

[hemtt.build]
optional_mod_folders = false

[hemtt.release]
sign = true 
archive = false
